site_name: Общая база знаний Павла Бойко

nav:
  - Организация труда: organisation/README.md
  - Науки:
    - Физика: 
      - Техническая механника: sciences/phisics/README.md
      - Детали машин:
      - Сопротивление материалов: 
    - Общественные науки:
      - История:
      - Социология:
      - Экономика:
    - Психология:
  - Профессии: 
    - Производственные:
      - Столярное дело: professions/README.md
      - Слесарное дело:
      - Литейное дело:
      - Сварные работы:
    - Строительные:
      - Строительство сооружений:
        - Земляные работы:
        - Бетон:
        - Работа с блочными материалами:
        - Плотницкие работы:
        - Кровельные работы:
      - Отделка внешняя и внутренняя:
      - Коммуникации:
        - Электрика:
        - Сантехника:
        - Отопление:
  - Искусство:
    - Музыка:
    - Изобразительное искусство: 
    - Кино:
  - Планирование:


site_author:
    p_boyko